
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 16:37:05 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 13;
  public static final int READ = 6;
  public static final int IDENT = 28;
  public static final int PLUS = 9;
  public static final int RBRACE = 24;
  public static final int RPAREN = 20;
  public static final int EQUAL = 14;
  public static final int CHAR = 29;
  public static final int SEMI = 17;
  public static final int NAMESPACE = 8;
  public static final int PLUS_PLUS = 15;
  public static final int LBRACE = 23;
  public static final int LPAREN = 19;
  public static final int COMMA = 18;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int PROG = 2;
  public static final int MINUS = 10;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int TWO_DOUBLE_DOT = 25;
  public static final int NEW = 4;
  public static final int BOOL = 26;
  public static final int MINUS_MINUS = 16;
  public static final int LSBRACE = 21;
  public static final int MUL = 11;
  public static final int VOID = 7;
  public static final int RSBRACE = 22;
}

