
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 02 13:29:30 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 42;
  public static final int CONST = 3;
  public static final int NAMESPACE = 10;
  public static final int MINUS_MINUS = 26;
  public static final int LPAREN = 31;
  public static final int GREATER = 18;
  public static final int SEMI = 27;
  public static final int LESS = 20;
  public static final int MINUS = 12;
  public static final int RPAREN = 32;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int BOOL = 39;
  public static final int COMMA = 29;
  public static final int DOUBLE_DOT = 28;
  public static final int DIV = 14;
  public static final int LESS_EQUAL = 21;
  public static final int DIFFERENT = 17;
  public static final int PLUS = 11;
  public static final int IF = 4;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int LSBRACE = 33;
  public static final int RETURN = 8;
  public static final int PLUS_PLUS = 25;
  public static final int EQUAL = 24;
  public static final int GREATER_EQUAL = 19;
  public static final int RSBRACE = 34;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int NUMBER = 40;
  public static final int MOD = 15;
  public static final int IDENT = 41;
  public static final int VOID = 9;
  public static final int TWO_DOUBLE_DOT = 37;
  public static final int ELSE = 38;
  public static final int LBRACE = 35;
  public static final int READ = 7;
  public static final int RBRACE = 36;
  public static final int PROG = 2;
  public static final int EQUAL_EQUAL = 16;
  public static final int PRINT = 6;
}

